name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install backend dependencies
      run: |
        cd backend
        pip install -r requirements.txt
    
    - name: Install frontend dependencies
      run: |
        cd frontend
        pip install -r requirements.txt
    
    - name: Run basic validation
      run: |
        echo "Validation passed"

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    # 🔍 Debug step added here
    - name: Debug DockerHub secrets
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        echo "Checking DockerHub Username..."
        echo "DOCKERHUB_USERNAME is: $DOCKERHUB_USERNAME"
        echo "Checking DockerHub Token length..."
        echo "Token length is: ${#DOCKERHUB_TOKEN}"

    - name: Login to DockerHub
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    
    - name: Build and push backend
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: karimaji143/backend:latest
    
    - name: Build and push frontend
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: true
        tags: karimaji143/frontend:latest
    
    - name: Build and push logger
      uses: docker/build-push-action@v4
      with:
        context: ./logger
        push: true
        tags: karimaji143/logger:latest
    
    - name: Send success notification
      if: success()
      run: |
        echo "Deployment successful for commit ${{ github.sha }}"
    
    - name: Send failure notification
      if: failure()
      run: |
        echo "Deployment failed for commit ${{ github.sha }}"
        exit 1
